composer/packagist

src/Packagist/WebBundle/Package/SymlinkDumper.php
Old format:
- **latest**: until 10 hours before 1st day of current month.
- **active**: 10-60 hours before 1st day of current month.
- **stale**: 60-180 hours before 1st day of current month.
- **archived**: more than 180 hours before 1st day of current month.
New format:
- **latest**: until monday last week.
- **YYYY-MM**: month block (03, 06, 09, 12), excluding what is in latest.
- **YYYY**: year, excluding current
- **archived**: Everything older than 2012
Rationale:
* Split into smaller groups, resulting in faster download. This becomes a problem when Packagist is overloaded and/or the user has a slow connection - Composer times out.
* Greatly reduces the changes to old providers. With the previous strategy, packages were switching constantly, causing cascading changes to all …
=> New splitting strategy for providers

app/Resources/FOSUserBundle/views/Profile/show.html.twig
=> Rename Bitbucket POST service to hook

src/Packagist/WebBundle/Resources/views/Web/index.html.twig
Could be nice to have it on quick info homepage.
=> Add a link for Package Versions usage documentation

src/Packagist/WebBundle/Resources/public/js/search.js
used the size of the desktop http://getbootstrap.com/css/#responsive-utilities
=> Autofocus search field if width more 992px

src/Packagist/WebBundle/Controller/ApiController.php
=> check if payload equals bitbucket push event

src/Packagist/WebBundle/Controller/PackageController.php
=> sort by trendiness if redis is available

src/Packagist/WebBundle/Package/Updater.php
=> allowed table elements returned by github api

src/Packagist/WebBundle/Controller/ApiController.php, src/Packagist/WebBundle/Controller/FeedController.php, src/Packagist/WebBundle/Controller/PackageController.php
- avoid using deprecation logger methods on failure
- remove dead code (unused Template annotation, unused argument...)
- fix inline phpdoc helping IDE, to actually help them
=> Clean the code of controllers

src/Packagist/WebBundle/Resources/views/Package/abandon.html.twig
Because, seriously @Seldaek?! :wink:
=> Remove class from ending html tag

app/AppKernel.php, app/config/config.yml, composer.json, composer.lock
=> Enabled CORS for API URLs

src/Packagist/WebBundle/Controller/PackageController.php, src/Packagist/WebBundle/Entity/PackageRepository.php, src/Packagist/WebBundle/Resources/views/Package/suggesters.html.twig, src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
Closes #582.
Suggestions page content:
Package info box:
=> Suggesters information

src/Packagist/WebBundle/Package/SymlinkDumper.php
Allow the search to specify the type of package to search for.
Related to composer/composer#5454
=> Added type parameter to search

src/Packagist/WebBundle/Controller/PackageController.php
This pull request adds the following info in the  json response of viewPackageAction
dependents (count)
suggesters (count)
github_stars
github_watchers
github_forks
github_open_issues
language
=> Add more data in json response of viewPackageAction

src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
Replaces #616 as suggested on https://github.com/composer/packagist/pull/616#issuecomment-163931603.
* GitHub stargazers
* GitHub watchers
* GitHub network (forks)
* GitHub open issues
=> Add package aside extra links

src/Packagist/WebBundle/Controller/PackageController.php, src/Packagist/WebBundle/Controller/UserController.php, src/Packagist/WebBundle/Entity/PackageRepository.php
Closes #664.
@Seldaek I don't know how to proper handle search result. Could you give me some clues?
In a global way, am I missing some sections?
=> [WIP] Put abandonned package at end of the list

src/Packagist/WebBundle/Resources/public/js/charts.js
=> Y-axis had incorrect/duplicate labels, fixes #696

src/Packagist/WebBundle/Package/Updater.php
=> Allow all heading levels in readme

src/Packagist/WebBundle/Package/Updater.php
=> Allow colspan and rowspan attributes in readmes

src/Packagist/WebBundle/Resources/public/js/search.js
=> #744 Use scrollIntoView instead of calculating scrollTop

src/Packagist/WebBundle/EventListener/LoggedInUserCannotRegisterListener.php, src/Packagist/WebBundle/Resources/config/services.yml
=> Logged in user is redirected to homepage when accessing registration page

composer.json, composer.lock, src/Packagist/WebBundle/Package/Updater.php, src/Packagist/WebBundle/Tests/Package/UpdaterTest.php
solves #556 
The tests will fail till https://github.com/composer/composer/pull/5862 is merged.
=> add readme support for non github repos 

src/Packagist/WebBundle/Entity/User.php
=> add maintainer avatar_url to package detail JSON

composer.json, composer.lock
The codebase actually uses some PHP 7 features.
=> Fix the PHP requirement in the composer.json

src/Packagist/WebBundle/Resources/views/ApiDoc/index.html.twig
See: https://twitter.com/seldaek/status/943843727164002304
=> Update the cache time description

src/Packagist/WebBundle/Controller/WebController.php
[`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped find them :+1:
=> [CS] Use Null Coalesce Operator

src/Packagist/WebBundle/Controller/ApiController.php
This pull request adds an endpoint to update the `repository` value of a package similar to the edit form that can be found on packagist.org.
Scenario is that if you have a github repository. Setup the webhook. Rename the github repository. Then future webhooks will fail with a 404 if you send the new github url instead of the existing. Therefore it would be helpful to have an api endpoint to update that value.
I tried to write a WebTestCase but failed to do so mainly because the `Package` entity triggers a git clone whenever you update the value of the `repository` property.
=> Package: add api endpoint to update package repository

app/config/config_prod.yml
=> Allow raw.github.com for images

src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
=> Fix the message about the update button

src/Packagist/WebBundle/Resources/views/ApiDoc/index.html.twig
Actually i am not sure what time is returned, but its definitely no the time of the last release (which would be very helpful indeed, but its not). So i assume its the date when the repo is registered on packagist.
=> Fix time documentation

src/Packagist/WebBundle/Package/Updater.php
* add support to details and summary tags.
* refs: #951.
=> Allow details/summary tags, refs #951

src/Packagist/WebBundle/Controller/WebController.php, src/Packagist/WebBundle/Resources/translations/messages.en.yml, src/Packagist/WebBundle/Resources/views/api_doc/index.html.twig
Context: https://twitter.com/seldaek/status/1148880016043728900
I've added an endpoint to fetch statistics, for now I've only implemented the one for total downloads ever, which I need. More could be added later if needed.
=> Added endpoint to fetch total downloads number.

README.md, composer.json, composer.lock, src/Packagist/WebBundle/Resources/views/macros.html.twig
I wanted to contribute to the code base, but found the readme lacking a little on a getting started guide.
I thought it would be helpful to update the readme with a bit more detailed instructions on getting setup for development.
Additionally, I've done a `composer update` and I've added the `incenteev/composer-parameter-handler` package that Symfony Standard Edition (v3.4) ships with to aid in a simplier setup.
=> Improve steps for setup of a dev environment

app/Resources/SchebTwoFactorBundle/views/Authentication/form.html.twig
Fixes https://github.com/composer/packagist/pull/1031#issuecomment-546258205
=> Add missing form-group wrapper

src/Packagist/WebBundle/Controller/PackageController.php, src/Packagist/WebBundle/Entity/Package.php, src/Packagist/WebBundle/Resources/views/package/view_package.html.twig, src/Packagist/WebBundle/Tests/Entity/PackageTest.php
Implements: https://github.com/composer/packagist/issues/985
=> Package: allow updates to be triggered by every logged in user if last updatedAt was > 24 hours ago

src/Packagist/WebBundle/Resources/translations/messages.en.yml, src/Packagist/WebBundle/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php
Follow up for: https://github.com/composer/packagist/pull/1046
=> Security advisory: fix workdir for zip download of advisories

src/Packagist/WebBundle/Resources/views/mirrors/index.html.twig
As title, add new Asia mirror site.
=> Add new Asia mirror

src/Packagist/WebBundle/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php
The source import was still depending on the 999999-dev version and the downloader wasn't ported to Composer 2.
=> SecurityAdvisories: fix source import with Composer 2

.travis.yml
This PR
💁‍♂️ For reference, see https://docs.travis-ci.com/user/job-lifecycle/.
=> Fix: Use appropriate job lifecycle sections

src/Packagist/WebBundle/Resources/views/web/index.html.twig
=> Do not use outdated PHP version

src/Packagist/WebBundle/Resources/translations/messages.en.yml, src/Packagist/WebBundle/Resources/views/api_doc/index.html.twig
fix: https://github.com/composer/packagist/issues/1119
=> api doc: add document for /api/create-package

src/Packagist/WebBundle/Command/RunWorkersCommand.php
`Symfony\Component\Filesystem\LockHandler` is deprecated and removed in Symfony 4, this replaces the use of the deprecated class with the `LockableTrait` that was added to the Console component for this exact use case.
=> Replace use of the deprecated LockHandler class

composer.json, composer.lock, phpstan.neon.dist, symfony.lock, tests/object-manager.php
Blocked by https://github.com/phpstan/phpstan-doctrine/issues/169
=> Add phpstan-doctrine

src/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php
Null pointer exception round the corner ;-)
=> Add missing initializer

web/js/search.js
=> Fix support for replacements as links in search results

src/Command/RunWorkersCommand.php, src/EventListener/LoggedInUserCannotRegisterListener.php, src/EventListener/RegistrationListener.php, src/Form/Handler/OAuthRegistrationFormHandler.php, src/Model/DownloadManager.php, src/Model/FavoriteManager.php, src/Model/ProviderManager.php, src/Package/Updater.php, src/Security/BruteForceLoginFormAuthenticator.php, src/Security/Provider/UserProvider.php, src/Security/RecaptchaHelper.php, src/Security/TwoFactorAuthManager.php, src/Security/TwoFactorAuthRateLimiter.php, src/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php, src/SecurityAdvisory/RemoteSecurityAdvisory.php, src/Service/GitHubUserMigrationWorker.php, src/Service/Locker.php, src/Service/SecurityAdvisoryWorker.php, src/Service/UpdaterWorker.php, src/Service/VersionCache.php, src/Twig/PackagistExtension.php, src/Util/UserAgentParser.php, src/Util/UserManipulator.php
- added missing typed properties
- added a couple missing constructor type hints
I've focused mostly on properties set in constructors (the most obvious ones) in this PR.
I'll propose more typed properties later on, in particular in entities, but these will need careful review to prevent uninitialized property errors wherever a `null` default value is assumed.
=> Typed properties

src/Command/PopulateDependentsSuggestersCommand.php, src/Controller/PackageController.php, src/Entity/Dependent.php, src/Entity/DependentRepository.php, src/Entity/PackageRepository.php, src/Entity/Suggester.php, src/Entity/SuggesterRepository.php, src/Package/Updater.php, templates/package/dependents.html.twig, tests/Package/UpdaterTest.php, translations/messages.en.yml
First step - will update the querying code later
=> Denormalize dependent/suggester storage

src/Security/AccountEmailExistsWithoutGitHubException.php, src/Security/AccountUsernameExistsWithoutGitHubException.php, templates/about/about.html.twig, templates/layout.html.twig, templates/user/edit.html.twig, templates/user/login.html.twig, templates/web/index.html.twig, translations/messages.en.yml
...and also "logout" to "log out", when used as a verb.
http://loginisnotaverb.com
=> Corrected “Login” (noun) to “Log in” (verb)

src/Service/Scheduler.php
These variables are already booleans.
=> Removed type casts not needed

src/Package/SymlinkDumper.php
This now hints at the deprecation of composer 1 support on packagist.org, to raise awareness
=> Update the warning message displayed to composer 1 users

src/Entity/SecurityAdvisory.php, src/Service/SecurityAdvisoryWorker.php
Based on https://github.com/composer/packagist/pull/1215
Only merge this once the previous code has been deployed and a update/advisory run have been triggered for the friendsofphp package
=> Security Advisory: cleanup changes from PR to introduce new remote id

templates/about/about.html.twig, templates/web/index.html.twig
Hi,
this PR mentions the GitLab hook integration for autoupdating packages and suggests to validate the syntax of composer.json before committing it for a new project.
Regards,
Tobias
=> Mention GitLab hook and checking file syntax

phpstan-baseline.neon, src/Service/GitHubUserMigrationWorker.php, src/Service/Locker.php, src/Service/QueueWorker.php, src/Service/Scheduler.php, src/Service/SecurityAdvisoryWorker.php, src/Service/UpdaterWorker.php, src/Service/VersionCache.php
Couldn't get rid of all due to the contract of `*Worker::process(..):array`
Maybe that's sth to improve in a follow up.
Let me know if you consider the changes not being defensive enough :)
=> Fixing PhpStan issues for Service namespace

web/js/search.js
Small shortcut when browsing explore/ (Browse) page
(also remove the old app_dev.php)
ℹ️ not tested locally
=> Autofocus instantsearch input on Browse packages page

src/Entity/SecurityAdvisory.php, src/SecurityAdvisory/AdvisoryParser.php, src/SecurityAdvisory/RemoteSecurityAdvisory.php, tests/SecurityAdvisory/AdvisoryParserTest.php
Addressing: https://github.com/composer/packagist/pull/1241#issuecomment-1024993233
=> SecurityAdvisory: improve title matching

src/SecurityAdvisory/RemoteSecurityAdvisory.php
Introduced by https://github.com/composer/packagist/pull/1241
=> SecurityAdvisory: CVE key might not exist

phpstan-baseline.neon, src/DataFixtures/DownloadFixtures.php, src/DataFixtures/PackageFixtures.php, src/DataFixtures/UserFixtures.php, src/EventListener/CacheListener.php, src/HealthCheck/MetadataDirCheck.php, src/Menu/MenuBuilder.php, src/Security/BruteForceLoginFormAuthenticator.php, src/Security/EmailVerifier.php, src/Security/GitHubAuthenticator.php, src/Security/Provider/UserProvider.php, src/Security/RecaptchaHelper.php, src/Security/TwoFactorAuthManager.php, src/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php, src/SecurityAdvisory/RemoteSecurityAdvisory.php, src/Twig/PackagistExtension.php, src/Validator/Password.php
This time various smaller namespaces
=> Fixing PHPStan issues in various smaller namespaces

composer.lock, phpstan-baseline.neon, src/Command/IndexPackagesCommand.php, src/Controller/ApiController.php, src/Entity/PackageRepository.php, src/Entity/PhpStatRepository.php, src/Entity/SecurityAdvisoryRepository.php, src/Entity/VersionRepository.php, src/Package/SymlinkDumper.php, src/Package/Updater.php
Closes #1232 (@staabm feel free to reopen one rebased if needed, I included your fixes here)
=> Update all deps, fix some phpstan errors

.editorconfig, README.md
=> Clean up - prettify markdown & add editorconfig

README.md, docker-compose.yaml
=> Extending docker setup

composer.json, composer.lock, src/Audit/AuditRecordType.php, src/Entity/AuditRecord.php, src/Entity/AuditRecordRepository.php, src/EventListener/PackageListener.php, tests/Audit/PackageAuditRecordTest.php
Lots to do still in AuditRecordType - but this lays the foundation down already so would be good to merge as first step.
=> Get started on audit log functionality

templates/api_doc/index.html.twig
Fixes https://github.com/composer/packagist/issues/1366
=> API: fix stats.json example URLs in docs

templates/web/index.html.twig
small PR passing by the website homepage
https://www.php.net/supported-versions.php
=> Do not use outdated PHP version on homepage example

templates/api_doc/index.html.twig
This will help devs to understand the issue (assuming they read the documentation). See https://github.com/composer/packagist/issues/1393
=> Mention the partial data for the v1 format in API docs

config/packages/security.yaml, src/Controller/UserController.php, src/Entity/TemporaryTwoFactorUser.php, src/Entity/User.php, src/Form/Type/EnableTwoFactorAuthType.php, src/Validator/TwoFactorCode.php, templates/user/enable_two_factor_auth.html.twig
Note: this will invalidate all current remember me cookies
=> 2FA changes should invalidate session

src/Form/ChangePasswordFormType.php, src/Form/EventSubscriber/FormBruteForceSubscriber.php, src/Form/EventSubscriber/FormInvalidPasswordSubscriber.php, src/Form/Extension/RecaptchaExtension.php, src/Form/ResetPasswordFormType.php, src/Form/Type/InvisibleRecaptchaType.php, src/Form/Type/ProfileFormType.php, src/Security/BruteForceLoginFormAuthenticator.php, src/Security/RecaptchaContext.php, src/Security/RecaptchaHelper.php, src/Twig/PackagistExtension.php, src/Validator/RateLimitingRecaptcha.php, src/Validator/RateLimitingRecaptchaValidator.php, templates/forms.html.twig, templates/layout.html.twig, templates/reset_password/reset.html.twig, tests/Security/RecaptchaHelperTest.php, tests/Validator/RateLimitingRecaptchaValidatorTest.php
The 2FA code on login is already protected by the Symfony bundle that limits 5 attempts in 15min.
=> Protect user password fields with ReCaptcha after 3 failed attempts

src/Controller/ProfileController.php, tests/Controller/ProfileControllerTest.php
Similar to https://github.com/composer/packagist/pull/1409. Any email change should also reset any pending password request as they were sent to the old email.
=> Profile: email change should reset password request

src/Controller/RegistrationController.php, templates/registration/register.html.twig
Bug: when `APP_RECAPTCHA_ENABLED=false` in .env then the registration form won't work locally.
=> Fix registration form not working in local environments

tests/Controller/AboutControllerTest.php, tests/Controller/ApiControllerTest.php, tests/Controller/ChangePasswordControllerTest.php, tests/Controller/ControllerTestCase.php, tests/Controller/FeedControllerTest.php, tests/Controller/ProfileControllerTest.php, tests/Controller/RegistrationControllerTest.php, tests/Controller/ResetPasswordControllerTest.php, tests/Controller/UserControllerTest.php, tests/Controller/WebControllerTest.php
as mentioned in #1439 so that we dont forget to setup/teardown and have a transaction everywhere.
=> Introduce a ControllerTestCase with getEm(), assertFormError()

css/app.scss, src/Controller/ApiController.php, templates/api_doc/index.html.twig, tests/Controller/ApiControllerTest.php
=> Add Bearer authentication support as alternative
