- src/Packagist/WebBundle/Resources/views/Web/index.html.twig
This PR
Since composer not only provides PSR-0, but PSR-4 and classmap autoloading support, it makes sense to update this section to be less specific.
> Fix: Update autoloading information on home page

- src/Packagist/WebBundle/Package/SymlinkDumper.php
- src/Packagist/WebBundle/Tests/Package/SymlinkDumperTest.php
This is a respin of #463
@Seldaek mentioned that the 2014 listing was always getting updated, this is true because we are at the beginning of the year.
This fixes it by calculating the last 4 trimesters before today. The rest of the logic remains unchanged.
This PR also adds a `getTargetListingBlocks` method that declares all blocks, this simplifies the code of `getTargetListing` and allows for easier testing.
And yeah, unit tests were added too.
Sample of generated blocks:
```
2014-12-31:
'latest'  => '2014-12-22'
'2014-10' => '2014-10-01'
'2014-07' => '2014-07-01'
'2014-04' => '2014-04-01'
'2014-01' => '2014-01-01'
'2013'    => '2013-01-01'
'2012'    => '2012-01-01'
2015-01-01:
'latest'  => '2014-12-22'
'2015-01' => '2015-01-01'
'2014-10' => '2014-10-01'
'2014-07' => '2014-07-01' …
```
> Splitting strategy: always keep 4 last trimesters

- src/Packagist/WebBundle/Controller/UserController.php
- src/Packagist/WebBundle/Entity/Package.php
- src/Packagist/WebBundle/Form/Handler/OAuthRegistrationFormHandler.php
> Fix: Undefined classes

- src/Packagist/WebBundle/Controller/WebController.php
`search.json?q=something&callback=my_call`
Will trigger the addition of a wrapper on the json return, allowing api calls from JS.
> Adding JSONP support

- src/Packagist/WebBundle/Package/Updater.php
Don't block all package updates due to one invalid branch
> Keep dev-versions up to date for valid branches

- doc/schema.xml
- src/Packagist/WebBundle/Command/IndexPackagesCommand.php
- src/Packagist/WebBundle/Controller/WebController.php
- src/Packagist/WebBundle/Form/Model/OrderBy.php
- src/Packagist/WebBundle/Form/Model/SearchQuery.php
- src/Packagist/WebBundle/Form/Type/OrderByType.php
- src/Packagist/WebBundle/Resources/public/css/main.css
- src/Packagist/WebBundle/Resources/public/js/search.js
- src/Packagist/WebBundle/Resources/views/Web/searchForm.html.twig
- src/Packagist/WebBundle/Tests/Controller/WebControllerTest.php
This pull request fixes the issue #365, in a slight different way than https://github.com/composer/packagist/pull/481.
It enables to sort by multiple ordered field, using HTML or JSON.
Even though the user interface does not permit it, as it may not be user friendly, the API does support a combination of ordering parameters.
Even if at the moment it may not be needed, it might come in handy when you decide to add other criterias to order by.
Below are some screenshots:
By downloads:
By favorites:
It also comes with automated tests.
Please be aware that these tests should not be run on a production machine, as they first drop / create the database to ensure isolation.
> Sorting of search results by multiple ordered fields

- src/Packagist/WebBundle/Resources/views/Web/searchForm.html.twig
This makes the search form fill all the width on mobile devices. A wider search form looks way more usable to me:
Before:
After:
> Make search field 100% wide on mobile

- src/Packagist/WebBundle/Resources/public/css/main.css
It now fills the entire row, instead of just the text/icon.
> Make navigation dropdown click area larger

- src/Packagist/WebBundle/Resources/public/css/main.css
Forcing subpixel-antialiasing stops Safari falling back to traditional anti-aliasing during animation of the dropdown menus.  The usual anti-aliasing switch makes the navbar text appear thin and wiry.
> Set subpixel antialiasing for navbar

- src/Packagist/WebBundle/Controller/ApiController.php
- src/Packagist/WebBundle/Tests/Controller/ApiControllerTest.php
I've noticed that Packagist doesn't work with urls like this:
ssh://git@stash.xxxxxx.com/yyyyyyy/standard-edition.git
If you try to create a *post receive hook* you'll get "Could not parse payload repository URL" error message.
I've modified src/Packagist/WebBundle/Controller/ApiController.php adding support for **ssh://git@**
So now even Atlassian Stash will work with Packagist, sending hooks when a repository is updated.
> added support for ssh protocol in updatePackageAction

- src/Packagist/WebBundle/Resources/views/Web/submitPackage.html.twig
The community link on https://packagist.org/packages/submit points to https://getcomposer.org/doc/06-community.md (which leads to a 404). It should point to https://getcomposer.org/doc/07-community.md
> Fixed link to community on submit page

- src/Packagist/WebBundle/Resources/views/About/about.html.twig
This documentation is now on the about page, not on the profile page.
> Fix the reference to the doc about how to update packages

- src/Packagist/WebBundle/Entity/DevRequireLink.php
- src/Packagist/WebBundle/Entity/Package.php
- src/Packagist/WebBundle/Entity/RequireLink.php
- src/Packagist/WebBundle/Entity/Tag.php
If the names are not unique, SQLITE will throw a fit and refuse to create the schema, e.g.:
```
$ app/console doctrine:schema:create
ATTENTION: This operation should not be executed in a production environment.
Creating database schema...
[Doctrine\ORM\Tools\ToolsException]
Schema-Tool failed with Error 'An exception occurred while executing 'CREATE INDEX package_name_idx ON link_require (version_id, packageName)':
SQLSTATE[HY000]: General error: 1 index package_name_idx already exists' while executing DDL: CREATE INDEX package_name_idx ON link_require (version_id, packageName)
[Doctrine\DBAL\Exception\TableExistsException]
An exception occurred while executing 'CREATE INDEX package_name_idx ON link_require (version_id, packageName)':
SQLSTATE[HY000]: General error: 1 index …
```
> Make index names unique

- src/Packagist/WebBundle/Controller/ApiController.php
I was speaking to @alcohol on IRC today and he confirmed my thought that there is no way to programatically add packages packagist. So I'm starting the effort towards a PR to add this functionality.
The use case is Drupal. I'm trying to look for a way that as soon as a new module is added to drupal.org it also gets added to packagist under the drupal namespace. I believe @dbuytaert owns the drupal namespace, drupal.org could use his API key to create the packages, then even add the module maintainer as a maintainer on packagist if we store packagist usernames as part of the drupal.org profiles.
We already have an endpoint in the packagist API for updating packages, which is awesome, but many packages are not already there so we need an automated way to add them.
> Create endpoint for API

- src/Packagist/WebBundle/Controller/ApiController.php
- src/Packagist/WebBundle/Tests/Controller/ApiControllerTest.php
This allows us to create webhooks for URLs that have port numbers in them (specifically `ssh://` running under custom port).
I've added the test as well, but haven't run them, haven't set it up properly yet.
> Allow (optional) port number in repository URL

- src/Packagist/WebBundle/Resources/views/Web/list.html.twig
The existing "No packages found" message seems a bit too subtle - this Bootstrap alert CSS should help boost its visibility.
> Increase the visibility of "No packages found."

- src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
Fixes #382 
This will show the package type below the `Language:` info.
> Show the package type in the package view

- src/Packagist/WebBundle/Resources/views/Package/versionDetails.html.twig
- src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
Fixes #577 
This PR checks if the `expandedVersion` has a license, and if not, displays a warning.
I'm not sure about the exact wording, any wishes/ideas?
> Add a warning in the package view if no license was found for the current version

- src/Packagist/WebBundle/Controller/PackageController.php
- src/Packagist/WebBundle/Resources/public/css/main.css
- src/Packagist/WebBundle/Resources/views/Package/dependents.html.twig
Just added a counter on dependents page.
I also made a quick-fix on CSS for package list that hide the title line.
Before:
After:
> Show deps count on dependents page

- src/Packagist/WebBundle/Form/Type/SearchQueryType.php
There is no JS code reading the prototype to add elements in the collection. The UI hides the fields and builds links separately.
> Avoid creating a useless prototype for the search ordering form

- src/Packagist/WebBundle/Resources/public/css/main.css
Consider this the lowest of the low in priority. :smile: 
Most of the current fonts used in `<pre>` do not have monospaced support [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character)
This can lead to deformities for people who try to be too smart for their own good, like myself.
Example:
[https://packagist.org/packages/foundry/masonry](https://packagist.org/packages/foundry/masonry)
The fonts in play are.
In [`pre, code`](https://github.com/composer/packagist/blob/d8ccd79956b4bc7d7d27de00419341c28c36b64b/src/Packagist/WebBundle/Resources/public/css/main.css#L30-L36):
* Consolas :x:
* Courier New :x:
* Courier :x:
* monospace :x:
In [`code`](https://github.com/composer/packagist/blob/master/web/libs/bootstrap-3.3.5/css/bootstrap.min.css) (imported from bootstrap): …
> Better monospaced font for box drawing

- src/Packagist/WebBundle/Resources/public/css/main.css
I tried to fix #614. Please let me know what you think about it or the changes I need to make. Thanks!
> Improved the styles of tables included in the README file

- src/Packagist/WebBundle/Command/DumpPackagesCommand.php
Now if DumpPackagesCommand fails due to any kind of exception thrown inside SymlinkDumper (it can be caused by filesystem problems or mysql server connectivity issues for example), - the lock aquired before SymlinkDumper is executed stays unreleased. 
This causes impossibility of aquiring this lock during the next DumpPackagesCommand run. 
This patch releases lock regardless of whether dump process was successful or not.
> Make possible next runs of DumpPackagesCommand after SymlinkDumper's exceptions thrown

- src/Packagist/WebBundle/Resources/public/js/search.js
I'm not sure about Mac... Does it use Ctrl for opening links in a new tab? Does that flag `ctrlKey` too?
> #656 Ctrl + Enter to open search result in new tab

- src/Packagist/WebBundle/Resources/views/Web/index.html.twig
Because it's not safe to require an unbound version, even if for PHP. :wink:
> Improve the way of php requirement on homepage

- src/Packagist/WebBundle/Resources/views/About/about.html.twig
I've changed the long paragraph to a list with bullets so that the steps to set up the hook are more readable.
**Before this PR**
**After this PR**
> Made the steps to set up the hook more readable

- src/Packagist/WebBundle/Controller/WebController.php
This is a follow-up to #692.
When someone is not using the latest version of composer (which includes the type parameter for the search), then searching for a package includes the type parameter placeholder. E.G (`https://packagist.org/search.json?q=symfony&type=%type%`). So the placeholder needs to be removed from the type query string.
> Replace type placeholder in the search

- src/Packagist/WebBundle/Form/Type/PackageType.php
This should be e.g. ("for example") rather than i.e. ("in other words"). See [this very serious grammar reference](http://theoatmeal.com/comics/ie) for more information.
Context: https://packagist.org/packages/submit
> changes i.e. to e.g.

- app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
- app/Resources/FOSUserBundle/views/Profile/show.html.twig
- src/Packagist/WebBundle/Menu/MenuBuilder.php
- src/Packagist/WebBundle/Resources/config/services.yml
- src/Packagist/WebBundle/Resources/translations/messages.en.yml
- src/Packagist/WebBundle/Resources/views/ApiDoc/index.html.twig
- src/Packagist/WebBundle/Resources/views/Explore/explore.html.twig
- src/Packagist/WebBundle/Resources/views/Explore/popular.html.twig
- src/Packagist/WebBundle/Resources/views/Package/abandon.html.twig
- src/Packagist/WebBundle/Resources/views/Package/browse.html.twig
- src/Packagist/WebBundle/Resources/views/Package/dependents.html.twig
- src/Packagist/WebBundle/Resources/views/Package/edit.html.twig
- src/Packagist/WebBundle/Resources/views/Package/providers.html.twig
- src/Packagist/WebBundle/Resources/views/Package/stats.html.twig
- src/Packagist/WebBundle/Resources/views/Package/submitPackage.html.twig
- src/Packagist/WebBundle/Resources/views/Package/suggesters.html.twig
- src/Packagist/WebBundle/Resources/views/Package/viewVendor.html.twig
- src/Packagist/WebBundle/Resources/views/User/favorites.html.twig
- src/Packagist/WebBundle/Resources/views/User/packages.html.twig
- src/Packagist/WebBundle/Resources/views/User/profile.html.twig
- src/Packagist/WebBundle/Resources/views/Web/list.html.twig
- src/Packagist/WebBundle/Resources/views/Web/searchSection.html.twig
- src/Packagist/WebBundle/Resources/views/Web/stats.html.twig
- src/Packagist/WebBundle/Resources/views/layout.html.twig
This commit moves labels and texts from the HTML templates into `translations/messages.en.yml` in order to allow localization and/or renaming (e.g. "package" => "plugin" as used for plugins.roundcube.net)
Templates with lots of content and instructions are subject to be moved into `translations/<template>.en.html` for easy translation.
Although not yet fully complete I hope you can accept this as a start for full localization of the Packagist site.
> Use localized strings in page views and templates

- src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
This uses [highlight.js](https://highlightjs.org/) to highlight content in all `pre` and `code` elements inside `div.readme`.
Includes via Cloudflare: https://cdnjs.com/libraries/highlight.js/
> added readme highlighting, issue #526

- src/Packagist/WebBundle/Resources/public/css/main.css
Using the color #f28d1a plus look better , easier to read the code (that is in black) .
> A simple change - pre border using #f28d1a

- src/Packagist/WebBundle/Resources/views/About/about.html.twig
The menu item "Webhooks & Services" does not longer exist. It is now named "Integrations & services".
> Change github menu item name in packagist "GitHub Service Hook HowTo"

- src/Packagist/WebBundle/Resources/config/services.yml
- src/Packagist/WebBundle/Util/UserManipulator.php
I started working on https://github.com/composer/packagist/issues/65 but I found out, that the `UserManipulator` is broken since [upgrade to dev version of FOSUserBundle](https://github.com/composer/packagist/commit/b6588d10de4bba3f10263c0e38cba9efded09d18#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R41) (it is not possible to call `php app\console fos:user:create`).
This PR adds the missing dependencies.
> Add missing services for UserManipulator

- src/Packagist/WebBundle/Package/Updater.php
- src/Packagist/WebBundle/Tests/Package/UpdaterTest.php
This tries to fix #764 by only removing the first `<h1>` element if it's the first actual element of the README file.
> Improve Updater to not remove useful README titles

- src/Packagist/WebBundle/Entity/Package.php
Per <https://github.com/composer/packagist/issues/461#issuecomment-225888618>, and in light of the conversation at #163, I thought this might help users understand how to gain permission to submit packages under a vendor namespace owned by another user.
Feel free to suggest/make wording changes, or to reject this entirely if you feel it isn't helpful.
> Add note about vendor permissions for a maintainer

- src/Packagist/WebBundle/Controller/FeedController.php
This will make it possible for third party clients to determine the latest release date from a simple HEAD request, rather than downloading the whole body and checking the `<pubDate>` / `<updated>` value.
> Set version feed Date header to latest release date

- src/Packagist/WebBundle/Resources/public/js/search.js
- src/Packagist/WebBundle/Resources/views/layout.html.twig
If you have a filter activated and you search for something else, you may not realize a filter is active.
I added the active filter widget at the top of the sidebar.
> Add active filter widget

- src/Packagist/WebBundle/Resources/config/algolia_settings.yml
I tweaked the ranking formula to improve relevancy. You can try it on the `packagist_prod_replica` index. (no reindexing required).
`popularity` is between 0 and 10 so it create [a lot of ties](https://www.algolia.com/doc/guides/ranking/ranking-formula/), that's why we can put it so high in the ranking formula.
We search first in the package name and then it tags. It helps finding templating engine when you search _"templating"_ for instance.
Then if every criteria are the same, we promote a package that is not deprecated compare to a deprecated one. We could even add the trendiness after that for instance.
Let me know what you think :)
---
Live testable version available here: https://piano-tuner-rhinoceros-60112.netlify.com
> Improve Algolia relevancy

- src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
Currently avatars of maintainers are only available in 48x48 pixels which makes them blurry on HiDPI screens. We can fix that by adding the `srcset` attribute.
Before/After:
> Add HiDPI version of maintainer gravatars

- src/Packagist/WebBundle/Controller/WebController.php
- src/Packagist/WebBundle/Resources/config/algolia_settings.yml
- src/Packagist/WebBundle/Resources/public/js/search.js
- src/Packagist/WebBundle/Resources/views/layout.html.twig
I added backward compatibility for link like https://packagist.org/search/tags=templating
In the meantime, I switch tags to checkbox link so they can be combined and I added search for tags.
> Add tags link backward compat

- src/Packagist/WebBundle/Controller/ApiController.php
GitHub and GitLab both send `$payload['repository']['url']`, but only GitLab's payload contains `$payload['project']`.
This ensures that the proper URLs are used from webhook payloads when GitLab is configured with nonstandard URLs (for example, when developing integrations in a local instance of gitlab-development-kit).
> Fix webhook source identification

- app/AppKernel.php
- src/Packagist/WebBundle/Command/CompileStatsCommand.php
- src/Packagist/WebBundle/Command/DumpPackagesCommand.php
- src/Packagist/WebBundle/Controller/WebController.php
- src/Packagist/WebBundle/Package/Updater.php
- src/Packagist/WebBundle/PackagistWebBundle.php
- src/Packagist/WebBundle/Tests/Controller/WebControllerTest.php
I've cleaned up some unused imports. This can save us some lines :put_litter_in_its_place: 
[`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped find them.
> [CS] Remove unused imports

- src/Packagist/WebBundle/Resources/public/js/search.js
This is a suggested solution for #849 where the focus on the search bar on pages where you probably want to do something other than search makes the site confusing/hard particularly for those with accessibility issues.  If there are other pages where the search bar _should_ be focussed, perhaps we can extend this patch to include those but I hope this works as a starting point.
> Focus the search box on the main page only

- src/Packagist/WebBundle/Command/CompileStatsCommand.php
>>>
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
You have requested a non-existent service "solarium.client".
>>>
> Removed unused variable

- bin/.htaccess
This folder does not seem to be used since https://github.com/composer/packagist/commit/78180ff3a21db3f9f1b73b882b29b8feb6e9a2e0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
> Remove unused bin directory

- src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
The `Update` button depends on the `ROLE_UPDATE_PACKAGES`. but currently, having `ROLE_UPDATE_PACKAGES` without `ROLE_EDIT_PACKAGES` would still not display the button, as `has_actions` was checking `ROLE_EDIT_PACKAGES` twice (probably a bad copy-paste)
> Fix condition to display actions

- app/Resources/FOSUserBundle/views/Profile/show.html.twig
Before:
after:
Note that the design was already fine after revealing the token. (but it stays fine).
> Fix the rendering of the API token

- src/Packagist/WebBundle/Controller/PackageController.php
`$average` value is always lower case.
The calculation still was correct but it never executed the optimized code branch where all days get fetch with one redis call.
> Fix: daily stats calculation

- src/Packagist/WebBundle/Resources/views/Package/viewPackage.html.twig
A number of my colleagues were unable to find how to add a maintainer after scouring aggressively as the button isn't the most obvious in its purpose.
It's mostly because when a package has one maintainer (the owner), it looks like the avatar of the package owner, not a collection of maintainers.
This PR updates the view from this:
To this:
> Add headers to improve maintainers visibility

- src/Packagist/WebBundle/Resources/views/Web/index.html.twig
This should be changed in january to sth. like this:
```diff
- "php": "^5.6.37 || ^7.0",
+ "php": "^7.0.31 || ^7.1",
```
> do not use outdated PHP version for example

- src/Packagist/WebBundle/Resources/views/Web/index.html.twig
Follow up #968 
As PHP `7.1` receives security fixes only, `7.2` should be recommended
> do not use outdated PHP version. refs #968

- src/Packagist/WebBundle/Controller/WebController.php
These two error paths can (and thus should) be called at the very beginning of the method, thus saving precious computation time.
> Return failed searchAction calls as early as possible.

- src/Packagist/WebBundle/Controller/PackageController.php
This PR fixes the calculations of daily downloads when averaging monthly.
Before| Now
------------ | -------------
The total monthly downloads were divided by `30.41` | The total monthly downloads are divided by the actual number of days in the month, `28` to `31`
The whole month of the `from` date was taken into account | The `from` date is actually respected
**Example**: `from=2018-01-29` yielded an interval `2018-01-01` → `2018-01-31` for the first month | `from=2018-01-29` yields `2018-01-29` → `2018-01-31`
The whole month of the `to` date was taken into account | The `to` date is actually respected
**Example**: `to=2019-03-12` yielded an interval `2019-03-01` → `2019-03-31` for the last month | `to=2019-03-12` yields `2019-03-01` → `2019-03-12`
The total number of downloads for the …
> Fix monthly stats averages

- src/Packagist/WebBundle/Resources/views/user/favorites.html.twig
- src/Packagist/WebBundle/Resources/views/user/packages.html.twig
- src/Packagist/WebBundle/Resources/views/user/profile.html.twig
This PR makes two minor changes to the `user` templates:
- Only set `isActualUser` in the block where it's needed - see https://github.com/composer/packagist/pull/1031#discussion_r332588385
- Only render the <small> tag when we have content for it - see https://github.com/composer/packagist/pull/1031#discussion_r332588127
> Template tweaks

- src/Packagist/WebBundle/Resources/views/mirrors/index.html.twig
Based on recents finds: https://github.com/Webysther/packagist-mirror#-packagist-public-metadata-mirrors-around-the-world
> Added more mirrors

- src/Packagist/WebBundle/Controller/ApiController.php
- src/Packagist/WebBundle/Controller/PackageController.php
- src/Packagist/WebBundle/Entity/SecurityAdvisory.php
- src/Packagist/WebBundle/Entity/SecurityAdvisoryRepository.php
- src/Packagist/WebBundle/Resources/config/services.yml
- src/Packagist/WebBundle/Resources/public/css/main.css
- src/Packagist/WebBundle/Resources/translations/messages.en.yml
- src/Packagist/WebBundle/Resources/views/package/security_advisories.html.twig
- src/Packagist/WebBundle/Resources/views/package/version_list.html.twig
- src/Packagist/WebBundle/Resources/views/package/view_package.html.twig
- src/Packagist/WebBundle/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php
- src/Packagist/WebBundle/SecurityAdvisory/RemoteSecurityAdvisory.php
- src/Packagist/WebBundle/SecurityAdvisory/SecurityAdvisorySourceInterface.php
- src/Packagist/WebBundle/Service/Locker.php
- src/Packagist/WebBundle/Service/Scheduler.php
- src/Packagist/WebBundle/Service/SecurityAdvisoryWorker.php
- src/Packagist/WebBundle/Service/UpdaterWorker.php
- src/Packagist/WebBundle/Tests/SecurityAdvisory/RemoteSecurityAdvisoryTest.php
- src/Packagist/WebBundle/Tests/SecurityAdvisoryWorkerTest.php
This pull request integrates security advisories into packagist.org. It is built in a way to additional sources can be integrated.
**Users are able to:**
* see how many advisories are available for every package
* see which versions of a package are affected by one or more advisory
* see detailed information about advisories for a package
* query the data via an API
**Adjustments to the package view page:**
* number of security advisories
* red icon in the version list to see which versions are affected
**New package security advisory page**
* list all advisories for a package
* via the query param `version` matching advisories will be highlighted
> Security Advisories

- src/Packagist/WebBundle/Entity/SecurityAdvisory.php
- src/Packagist/WebBundle/Entity/SecurityAdvisoryRepository.php
- src/Packagist/WebBundle/SecurityAdvisory/RemoteSecurityAdvisory.php
- src/Packagist/WebBundle/Tests/SecurityAdvisory/RemoteSecurityAdvisoryTest.php
This allows security advisories to be displayed sorted by reported date to make it easier to see the newest advisories for a package first.
Note about the schema changes:
* I changed `affectedVersions` to `text` from `string` because some symfony/symfony advisories go past the 255 char limit and are being truncated
* Easiest way to apply the `reportedAt` column is to truncate the table and trigger a new update job for the advisory repo. As an alternative apply with DEFAULT NULL. Run a job and drop the default.
> Security Advisories: store reported date

- src/Packagist/WebBundle/Controller/PackageController.php
- src/Packagist/WebBundle/Entity/DownloadRepository.php
- src/Packagist/WebBundle/Entity/Version.php
- src/Packagist/WebBundle/Resources/public/css/main.css
- src/Packagist/WebBundle/Resources/public/js/charts.js
- src/Packagist/WebBundle/Resources/views/package/stats.html.twig
- src/Packagist/WebBundle/Resources/views/package/version_list.html.twig
- src/Packagist/WebBundle/Resources/views/package/view_package.html.twig
This implements package installs per major version as mentioned in https://github.com/composer/packagist/issues/1006
There is a toggle at the top of the version list which lets you switch between versions and major versions. Toggling will automatically select the fist version/major version in the list.
> Installs per package major version

- src/Packagist/WebBundle/Entity/Version.php
- src/Packagist/WebBundle/Package/Updater.php
- src/Packagist/WebBundle/Resources/views/package/view_package.html.twig
Requires funding support (https://github.com/composer/composer/pull/8453) to be merged into Composer and the composer/composer dep to be updated before this can be merged.
Displaying of funding info in the UI is pretty basic for now. It simply lists all links in the details section. Maybe someone can come up with a nicer way to display this? Maybe a button in that section that is a bit more obvious and then a modal with all the options?
*Requires the addition of a funding text column to the version table prior to deployment.*
> Display funding information for packages and expose funding info to Composer

- src/Packagist/WebBundle/SecurityAdvisory/RemoteSecurityAdvisory.php
- src/Packagist/WebBundle/Tests/SecurityAdvisory/RemoteSecurityAdvisoryTest.php
Currently if a security advisory only has a year set and no branch has a fix date then this falls back to the current date which means every time we reimport them from the git repository the reportedAt date gets updated.
Settings this to Year-01-01 for now to avoid updating that date all the time.
> SecurityAdvisory: fix reported date when only year is available

- src/Packagist/WebBundle/Resources/public/css/main.css
Currently, long funding links can overflow the sidebar:
Applying the same styling as the `.details` section fixes this:
> Fix funding links overflowing the sidebar

- src/Packagist/WebBundle/Entity/Version.php
Instead of sorting the funding sources when saving, we store them with the original sort order and only perform sorting when generating metadata. This allows the V2 algo to retain the same performance boost while ensuring the Packagist website presents the sources in the author's preferred order.
Fixes #1077
> Retain original funding sort order on website (fixes #1077)

- app/AppKernel.php
- app/Resources/HWIOAuthBundle/views/Connect/login.html.twig
- app/config/config.yml
- app/config/config_prod.yml
- app/config/defaults.yml
- app/config/routing.yml
- app/config/security.yml
- composer.json
- composer.lock
- src/Packagist/Redis/FailedLoginCounter.php
- src/Packagist/WebBundle/Controller/SecurityController.php
- src/Packagist/WebBundle/Resources/config/services.yml
- src/Packagist/WebBundle/Resources/views/layout.html.twig
- src/Packagist/WebBundle/Security/BruteForceLoginFormAuthenticator.php
- src/Packagist/WebBundle/Security/RecaptchaHelper.php
- src/Packagist/WebBundle/Tests/Security/BruteForceLoginFormAuthenticatorTest.php
- src/Packagist/WebBundle/Tests/Security/RecaptchaHelperTest.php
- src/Packagist/WebBundle/Twig/PackagistExtension.php
Protection is implemented via Google ReCaptcha.
After the third failed login attempt for a certain IP or username an v3 invisible recaptcha is displayed and required to login via username+password.
The counters are reset after 7 days of no failed login.
This uses Symfony guard authentication which replaces the previously used form_login.
> Login: add brute force protection

- src/Packagist/WebBundle/Controller/SecurityController.php
Regression which was introduced by #1082
This causes a 500 error when accessing pw reset URLs with invalid tokens e.g. https://packagist.org/resetting/reset/invalid-token
> FOS: still require a route called fos_user_security_login

- src/Packagist/WebBundle/Security/RecaptchaHelper.php
Fixes test failures introduced by https://github.com/composer/packagist/commit/e559612bba619903c649533649cbb85e141b7c7e
> Recaptcha: assert _username is always a string to increase/reset counters

- src/Packagist/WebBundle/Resources/views/mirrors/index.html.twig
- Remove `packagist.vrkansagara.in` mirror site because it's broken.
And it's not available.
- Set using this mirror site with following command:
```Bash
composer config -g repos.packagist composer https://packagist.vrkansagara.in
```
After setting up this mirror site, using following command to install a package:
```Bash
composer require nesbot/carbon
```
It should be worked to install this specific package successfully.
Throw following exceptions:
```Bash
[RuntimeException]
No composer.json present in the current directory, this may be the cause of the following excepti
on.
[Composer\Downloader\TransportException]
The "https://packagist.vrkansagara.in/packages.json" file could not be downloaded: Peer certifica
te CN=`arthurandersonaccountants.co.uk' did not match expected …
```
> Remove packagist.vrkansagara.in mirror site

- src/Packagist/WebBundle/Resources/translations/messages.en.yml
- src/Packagist/WebBundle/Resources/views/api_doc/index.html.twig
> API: add documentation for the security advisory endpoint

- composer.json
> Fix: Use https instead of http

- src/Packagist/WebBundle/Resources/public/css/main.css
- web/css/github/markdown.css
This adds a little hand to the `<summary>` element.
Before:
After:
This improves UX and also is the default behavior in GitHub:
<details>
<summary>Summary has a little hand</summary>
Here goes the details.
</details>
> Add little hand to summary element

- app/AppKernel.php
- composer.json
- composer.lock
- src/Packagist/WebBundle/Controller/Controller.php
- src/Packagist/WebBundle/Controller/ExploreController.php
- src/Packagist/WebBundle/Controller/PackageController.php
- src/Packagist/WebBundle/Controller/UserController.php
`WhiteOctoberPagerfantaBundle` is now abandoned and my `BabDevPagerfantaBundle` is the replacement for it.  The bundle is replaced with this pull request, and deprecated uses of the Pagerfanta API replaced as well.
> Upgrade Pagerfanta

- src/Packagist/WebBundle/Model/PackageManager.php
- src/Packagist/WebBundle/Resources/views/forms.html.twig
- src/Packagist/WebBundle/Twig/PackagistExtension.php
Some of the Twig integration was still using older class names, and the templates were using the deprecated filter tag.  These have been updated.
> Replace deprecated Twig uses

- composer.json
- composer.lock
- config/routes/hwioauth_fosub.yaml
- config/services.yaml
- phpunit.xml.dist
- src/Controller/ApiController.php
- src/Controller/Controller.php
- src/Controller/PackageController.php
- src/Controller/UserController.php
- src/Model/DownloadManager.php
- src/Twig/PackagistExtension.php
- symfony.lock
- Added `symfony/lock` component for the lockable trait to work on the worker command
- Checked in `symfony.lock` for Flex
- Set PHPUnit default version at 8.5 (matches current master)
- Replaced `$this->get()` use in controllers with DI (for both params and services)
- Removed local `csrf_token()` Twig function in favor of the one from the framework
> 4.4 Upgrade Tweaks

- src/Model/PackageManager.php
Package update jobs with a broken branch or failure currently return instead of the actual error and also do not email the maintainers because of `{"status":"errored","message":"An unexpected failure occurred","exception":[],"exceptionMsg":"An address can be an instance of Address or a string (\\\"array\\\") given).\",\"exceptionClass\":\"Symfony\\\\Component\\\\Mime\\\\Exception\\\\InvalidArgumentException\"}"`
> Package: fix update job failure email

- config/packages/nelmio_security.yaml
- allow AJAX request to www.google-analytics.com as they are needed by GA
- restrict Algolia rules to HTTPS, following their own recommendation anyway
- remove the non-HTTPS img-src for google analytics. This is blocked by blocking mixed content anyway.
> Update the CSP configuration

- web/js/view.js
I noticed that both package delete and version delete buttons show a plain `Are you sure?` confirmation message. IMO it’s better when the alert contains what you are about to delete and that you’re even going to delete that.
Ideally, for the package versions, it would tell the user the name of the version they’re about to delete. That’s because the delete buttons are pretty close to each other, avoiding misclicks.
> Make delete confirmation alerts more descriptive

- src/Controller/PackageController.php
The negation of a OR is not the OR of the negations. This was broken when switching that condition to include it in the early return (in https://github.com/composer/packagist/commit/c3f88efc5a96003eb38e368da96ce05cace013ec).
Closes #1181
> Fix conditions for displaying maintainer forms

- src/Package/V2Dumper.php
This make it easier to see it when a human look at the JSON returned by packagist, as the list of versions is quite long.
I got this idea while answering #1194
> Write the minified key at the beginning of the dumped file

- .env
I just cloned the projected. I followed the steps in the readme and got an error that `MAILER_DSN` was missing. 
This adds a nice default value for MAILER_DSN.
> Adding default MAILER_DSN

- web/css/main.css
`.wrapper .content h2 a` selector matches the readme header link field causing it to be dark grey instead of orange like any other links. Instead, it the rule should be amended to match only the package title in page header.
```markdown
```
**Before:**
**After:**
BTW I think it would be worth to introduce SCSS as there are many nested styles and rules that are repeated. Let me know if I can help with that.
> Fix readme h2 link color

- phpstan-baseline.neon
- src/Controller/UserController.php
- src/Form/Model/EnableTwoFactorRequest.php
- src/Form/Type/EnableTwoFactorAuthType.php
- templates/user/enable_two_factor_auth.html.twig
Prior to this change, user was able to change the 2FA secret into any value by manipulating hidden form field which might be a security concern. This can be fixed by temporarily using session to store the secret between requests. Please note it still generates a new secret each time you refresh the page.
I also changed the QR code writer to SVG for better resolution on Retina screens. Thanks to `user-select: all`, secret is fully selected with a single click which makes it even easier to copy, especially on mobile devices.
> use session to store 2fa secret between requests

- src/Entity/SecurityAdvisory.php
- src/Entity/SecurityAdvisoryRepository.php
- src/SecurityAdvisory/AdvisoryIdGenerator.php
- src/SecurityAdvisory/RemoteSecurityAdvisory.php
- src/Service/SecurityAdvisoryWorker.php
- templates/api_doc/index.html.twig
- tests/Entity/SecurityAdvisoryTest.php
- tests/SecurityAdvisoryWorkerTest.php
As per https://github.com/FriendsOfPHP/security-advisories/pull/595#issuecomment-948400214 we should not rely on the filenames.
This PR
* introduces a new advisory id which can be used by API consumers
* detects renamed friendsofphp advisory files and tries to matches them to existing advisories
Follow up PR to set the advisory id to unique https://github.com/composer/packagist/pull/1216
> Security Advisory: handle friendsofphp renaming advisory files

- config/services.yaml
- phpstan-baseline.neon
- src/Command/ConfigureAlgoliaCommand.php
Possibly a bug introduced with #1144, ran into it while setting up algolia.
Messed up the diff though.
Bug was the relative path here: 
```php
file_get_contents(__DIR__.'/../config/algolia_settings.yml')
```
> Fixing file path in algolia:configure command

- src/Package/Updater.php
Github accepts the attribute `align` for element alignment. See the differences in elements alignment at the start between [this README on Github](https://github.com/simple-icons/simple-icons/blob/06f09a265d3c9d3dee994f3fdcb245f115e840e1/README.md) and [the same on Packagist](https://packagist.org/packages/simple-icons/simple-icons).
I'm using here the same implementation used by [Python's PYPI README renderer](https://github.com/pypa/readme_renderer).
> Allow `align` attribute rendering READMEs

- src/Entity/SecurityAdvisory.php
- src/SecurityAdvisory/RemoteSecurityAdvisory.php
- tests/Entity/SecurityAdvisoryTest.php
- tests/SecurityAdvisory/RemoteSecurityAdvisoryTest.php
Adjusted the security advisory handling for temporary CVE ids as seen in https://github.com/FriendsOfPHP/security-advisories/pull/607/files
I wonder whether the title comparison should/can be done a bit more generic?
> SecurityAdvisory: handle temporary CVE-2022-xxx format

- src/Package/Updater.php
Add support for GitLab in README files as well.
- Convert relative links to absolute links,
pointing to the right repository subdirectory
- Fix path to images sources to embed them directly
Tested manually with [example package pixelbrackets/markdown-mini-page](https://packagist.org/packages/pixelbrackets/markdown-mini-page).
Before: [Missing screenshot](https://user-images.githubusercontent.com/1592995/152661116-5078ed64-aaff-4fb1-b889-85a07970d9a3.png)
After: [Having screenshot](https://user-images.githubusercontent.com/1592995/152661117-bdf5a2b5-f342-43d8-9768-649c1134f495.png)
As suggested in issue #1223 I tried to take a look at BitBucket as well,
but it turns out they generate hashes for all embedded image paths,
which can not be guessed (see …
> Support GitLab in README files

- src/Package/Updater.php
Followup for PR [1254](https://github.com/composer/packagist/pull/1254#issuecomment-1030864892)
with support for images in README files of packages hosted on BitBucket.
Tested manually on my local instance with the demo package https://bitbucket.org/pixelbrackets/composer-test,
see screenshot below.
> Follow up: Support BitBucket images in readme

- phpstan-baseline.neon
- phpstan.neon
- src/Command/CleanIndexCommand.php
- src/Command/CompileStatsCommand.php
- src/Command/DumpPackagesCommand.php
- src/Command/DumpPackagesV2Command.php
- src/Command/IndexPackagesCommand.php
- src/Command/MigrateDownloadCountsCommand.php
- src/Command/MigratePhpStatsCommand.php
- src/Command/RegenerateMainPhpStatsCommand.php
- src/Command/SymlinkMetadataMirrorCommand.php
- src/Command/UpdatePackagesCommand.php
This includes the proposal to use `__CLASS__` as unique identifier per command for `Locker` methods instead of `getName()` as this is nullable.
Promoted the `ini_set` issues to `phpstan.neon` - could be removed with php 8.1 update
While regerating the baseline a lot of issues dropped out of the baseline which i cannot take credit for. potentially caused by a missing update or phpstan update.
> Fixing PHPStan issues in Command namespace

- README.md
- config/services.yaml
- docker-compose.yaml
- src/Command/UpdateSecurityAdvisoriesCommand.php
- src/Entity/PackageRepository.php
- src/Entity/SecurityAdvisory.php
- src/Entity/SecurityAdvisoryRepository.php
- src/Entity/SecurityAdvisorySource.php
- src/SecurityAdvisory/FriendsOfPhpSecurityAdvisoriesSource.php
- src/SecurityAdvisory/GitHubSecurityAdvisoriesSource.php
- src/SecurityAdvisory/RemoteSecurityAdvisory.php
- src/SecurityAdvisory/RemoteSecurityAdvisoryCollection.php
- src/SecurityAdvisory/SecurityAdvisoryResolver.php
- src/SecurityAdvisory/SecurityAdvisorySourceInterface.php
- src/Service/Locker.php
- src/Service/Scheduler.php
- src/Service/SecurityAdvisoryWorker.php
- src/Service/UpdaterWorker.php
- templates/package/security_advisories.html.twig
- tests/Entity/SecurityAdvisoryTest.php
- tests/SecurityAdvisory/GitHubSecurityAdvisoriesSourceTest.php
- tests/SecurityAdvisory/RemoteSecurityAdvisoryTest.php
- tests/SecurityAdvisory/SecurityAdvisoryResolverTest.php
- tests/SecurityAdvisoryWorkerTest.php
This PR builds on top of https://github.com/composer/packagist/pull/1206 to add support for GitHub advisories
Unfortunately, using GitHub webhooks to get notified about new advisories might not be an option (requires GitHub App with additional permissions), so running the job after every package update might add new advisories only a while after they were created. It would also create a huge amount of unnecessary additional jobs.
Fetching all GitHub advisories in a single run limits the number of background job we generate. It also allows us to trigger them on a regular basis via a cron (every 5/10min) with the added command
Especially, the affected version range for data from the GitHub advisory database is a lot less accurate, therefore this is always using the FOPHP data if available.
> GitHub Security Advisories: import available advisories via single worker run

- src/Entity/SecurityAdvisory.php
- src/SecurityAdvisory/GitHubSecurityAdvisoriesSource.php
- tests/SecurityAdvisory/GitHubSecurityAdvisoriesSourceTest.php
Example: https://github.com/advisories/GHSA-xx8f-qf9f-5fgw
This currently merges the two advisories into a single one using the package name of the first and the version range of both.
> SecurityAdvisory: handle GitHub advisories affecting multiple packages

- composer.json
- composer.lock
- symfony.lock
Happens when trying to reset the EM in the QueueWorker after the EM was closed
[LogicException]
In ManagerRegistry.php line 54:
Resetting a non-lazy manager service is not supported. Try running "composer require symfony/proxy-manager-bridge".
> Fix: Resetting a non-lazy manager service is not supported.

- templates/about/about.html.twig
Hey all, 
I didn't see the set of allowed characters for a package mentioned anywhere on the site and after being forwarded to this regex
https://github.com/composer/packagist/blob/699c69d32f770b37b46469805e8ba9eb2ba6de6f/src/Entity/Package.php#L312
I felt that this could be helpful to document for others that end up looking. Happy to change the wording on this if need be.
> Add a note about the allowed characters for a package

- templates/about/about.html.twig
https://getcomposer.org/doc/08-community.md implies that the channel has moved. If this is not desired, feel free to close.
> Update IRC link to libera.chat

- esbuild.js
- js/app.js
- js/jquery.js
Don't ask me, I have no clue why this additional weird `jquery.js` workaround is needed
at least it fixes the issue with the navbar
> Readding bootstrap js

- js/search.js
#1313.
I feel like this may break stuff. I've done 10 minutes or so of testing, But I don't know packagist very well despite how much I use the public site and having this globally means accounting for a lot of things like this stealing focus from other inputs.
As an example: without the check for inputs as active elements this would break signing in (with a password that had a `/`).
Is there any chance that there could be abnormal keyboard inputs somewhere that don't use the input tag as they should?
> Make `/` keypress focus search input

- templates/about/about.html.twig
Hi,
Gitea recently added support for a Packagist webhook, enabling automatic updates for packages. I've added a section about how to enable it.
Regards,
Tobias
> Add Gitea webhook for Packagist

- src/Controller/PackageController.php
- src/Entity/Package.php
- src/Entity/PackageRepository.php
- src/Entity/VendorRepository.php
- src/Entity/VersionRepository.php
DB migration in case anyone cares:
```
ALTER TABLE package ADD vendor VARCHAR(191) NULL;
UPDATE package SET vendor = SUBSTRING_INDEX(`name`, '/', 1) where vendor IS NULL;
ALTER TABLE package CHANGE vendor vendor VARCHAR(191) NOT NULL;
CREATE INDEX vendor_idx ON package (vendor);
```
> Add vendor field to package table to avoid LIKE queries for vendor listings

- config/services.yaml
- src/Controller/ApiController.php
- src/Controller/ChangePasswordController.php
- src/Controller/GitHubLoginController.php
- src/Controller/PackageController.php
- src/Controller/ResetPasswordController.php
- src/Controller/UserController.php
- src/EventListener/CacheListener.php
- src/EventListener/RequestStatsListener.php
- src/EventListener/SecurityAdvisoryUpdateListener.php
This PR converts some remaining `@Route` and `@IsGranted` annotations to attributes and uses `#[AsEventListener]` and `#[AsEntityListener]` attributes to register EventListeners and Entity listeners, reducing the amount of configuration in `services.yaml`.
> Convert remaining annotations to attributes

- config/services.yaml
- src/Security/Provider/UserProvider.php
Another round of simplifying the `config/services.yaml` - thanks to the Autowiring and binding the arguments in the `_defaults` section, we are able to omit some configuration.
> Simplify services.yaml

- .github/workflows/continuous-integration.yml
- .github/workflows/lint.yml
- .github/workflows/phpstan.yml
- Makes use of awesome https://github.com/ramsey/composer-install action, which takes care of the caching, thus removing usage of deprecated `::set-output`.
- Bumping `actions/checkout` to `v3` (v2 uses deprecated Node v12)
- Setting `DATABASE_URL` via physical `env` for clarity
> [Chore][CI] Improve CI workflow

- templates/mirrors/index.html.twig
Added mirror located in Denmark.
Benchmark shows around 10 seconds of saved time over 20 installs from my location (Fyn, Denmark).
> Add Denmark mirror

- src/Entity/Version.php
- templates/package/view_package.html.twig
This is a complementary feature for the security support option added in https://github.com/composer/composer/pull/11271
If the package has a security support link provided in `composer.json`, this will add a "Security Policy" link on Packagist. For example:
> Add link to package security policy

- src/Controller/WebController.php
Hi. I noticed that the cache is saved html, which contains the data of the authorized user.  The data does not contain security sensitive information, but you can see the nickname of the last person who viewed this page 
It affected only `/php-statistics` page. The other pages with public cache control `NO_AUTO_CACHE_CONTROL_HEADER` is JSON not affected.
**STR**
1) Login to packagist
2) Open https://packagist.org/php-statistics
3) Open this page in incognito 
**Actual result** 
Depends on who last viewed this page when the cache was builded:
a) One the step 3. You will see the nickname of the last visited user
b) Or on step 2 you will see menu for non-authorized user
> Don't share private cache via CDN.

- templates/package/view_package.html.twig
Howdy 👋 
I noticed the URL for a packages Forks goes to the Network page on GitHub. Back in February, GitHub [introduced a new page](https://github.blog/changelog/2023-02-24-new-forks-page-view/), specifically for Forks of a package. I think this link makes more sense to now point to that page.
Thanks!
> change forks url to /forks

- src/Controller/ApiController.php
Additional fixes for #1374. The user can use an api token as GitHub secret and a custom webhook payload to change the URL of a package with more than 50k downloads.
> More protection from account takeovers

- templates/mirrors/index.html.twig
Since [Jul 30, 2021](http://web.archive.org/web/20210601000000*/https://php.cnpkg.org/), php.cnpkg.org is offline. So please remove from mirror recommendation to avoid consumption of community time.
> removed: `php.cnpkg.org`, reason: dead mirror

- src/Controller/PackageController.php
- src/Entity/SecurityAdvisory.php
- src/Entity/SecurityAdvisoryRepository.php
- src/Entity/SecurityAdvisorySource.php
- src/SecurityAdvisory/GitHubSecurityAdvisoriesSource.php
- src/SecurityAdvisory/RemoteSecurityAdvisory.php
- src/SecurityAdvisory/RemoteSecurityAdvisoryCollection.php
- src/SecurityAdvisory/SecurityAdvisoryResolver.php
- src/SecurityAdvisory/Severity.php
- templates/api_doc/index.html.twig
- templates/package/_security_advisory_list.html.twig
- templates/package/security_advisories.html.twig
- templates/package/security_advisory.html.twig
- tests/Controller/ApiControllerTest.php
- tests/Entity/SecurityAdvisoryTest.php
- tests/SecurityAdvisory/GitHubSecurityAdvisoriesSourceTest.php
- tests/SecurityAdvisory/RemoteSecurityAdvisoryTest.php
- tests/SecurityAdvisory/SecurityAdvisoryResolverTest.php
- tests/SecurityAdvisory/SeverityTest.php
- tests/SecurityAdvisoryWorkerTest.php
This fetches the severity for each advisory from the GitHub security advisory database and make the data available for Composer to use during `composer audit`.
The severity is currently returned/shown as part of `/api/security-advisories/` (I believe this is enough for Composer?) and the UI.
I am not sure if storing the severity as part of the `SecurityAdvisorySource` is necessary. I figured if we have multiple sources reporting the severity, we can calculate a median. Happy to remove this if people think this isn't necessary.
UI Example:
> Security advisories: store severity

- src/Entity/Package.php
- src/Package/Updater.php
- templates/package/view_package.html.twig
This pull request refers to #1406 and depends on [this other PR for Composer](https://github.com/composer/composer/pull/11734) (merged but actually to be yet included in a versioned release).
Provides some extra support for packages hosted on gitlab.com, in particular for stars and forks counters.
Considerations:
- I kept the original naming of attributes with the "github" prefix (e.g. github_stars) to avoid breaking stuff. Inaccurate, but effective
- I've introduced `isGitHub()` and `isGitLab()` functions in `App\Entity\Package` to wrap provider's guessing based on repository URL
> Improved support for GitLab

- composer.lock
- src/Command/ClearVersionsCommand.php
- src/Command/DumpPackagesCommand.php
- src/Command/DumpPackagesV2Command.php
- src/Command/IndexPackagesCommand.php
- src/Controller/PackageController.php
- src/Controller/UserController.php
- src/Entity/Package.php
- src/Entity/PackageRepository.php
- src/Entity/VersionRepository.php
- src/Model/PackageManager.php
- src/Package/SymlinkDumper.php
- src/Package/Updater.php
- src/Package/V2Dumper.php
- src/Service/UpdaterWorker.php
- templates/macros.html.twig
- templates/package/view_package.html.twig
- tests/Package/UpdaterTest.php
- translations/messages.en.yml
Replaces https://github.com/composer/packagist/pull/1402
> Repo jacking protection and cleanups

- config/packages/security.yaml
- config/services.yaml
- src/Menu/MenuBuilder.php
- templates/bundles/SchebTwoFactorBundle/Authentication/form.html.twig
- templates/layout.html.twig
- templates/user/login.html.twig
Clears the browser cookies, cache + storage on logout. Storage is currently not used as far as I can tell.
> Logout: add CSRF token and clear site data

- templates/api_doc/index.html.twig
Hi, this is just a minor fix for a typo on the API docs page. 
`we rather not do` -> `we'd rather not do`
> Fixed type (changed 'we' to "we'd")

- README.md
- src/Entity/Package.php
- src/Entity/Tag.php
- src/Entity/Version.php
- templates/package/view_package.html.twig
- tests/Entity/PackageTest.php
- tests/Entity/TagTest.php
- tests/Entity/VersionTest.php
> detect dev for install command

- src/Form/Type/ProfileFormType.php
- src/Validator/RateLimitingRecaptchaValidator.php
No need to pass `$value` to the verifier. The recaptcha library will extract the correct value from the request.
> Profile: fix edit settings with GitHub connected account

- README.md
- docker-compose.node.yaml
- docker-compose.yaml
Does npm install and npm run build once `docker compose up` is used.
Can put this to https://docs.docker.com/compose/profiles/ if needed. But dont think so.
- `version:` is not read from compose v2 anymore (always uses the latest)
- anonymous volumes can be now created without a top level entry in volume
> Add node/npm to compose file

- src/Controller/ResetPasswordController.php
- templates/reset_password/request.html.twig
Sorry, just another one. #1437
> Fix password reset form not working in local environments 

- src/Controller/ResetPasswordController.php
- src/Form/ChangePasswordFormType.php
- src/Form/RegistrationFormType.php
- src/Form/ResetPasswordFormType.php
- src/Validator/NotProhibitedPassword.php
- src/Validator/NotProhibitedPasswordValidator.php
- tests/Controller/ChangePasswordControllerTest.php
- tests/Controller/ProfileControllerTest.php
- tests/Controller/RegistrationControllerTest.php
- tests/Controller/ResetPasswordControllerTest.php
PR changes that you can't use your email address or your username as a password anymore.
We are aware that it's hard in general to get people to use really good passwords, but at least this crosses out the really dumb mistakes.
> Avoid simple passwords (e.g. email as password)

- src/Controller/ChangePasswordController.php
- src/Controller/GitHubLoginController.php
- src/Controller/ProfileController.php
- src/Security/UserNotifier.php
- templates/email/alert_change.txt.twig
Fixes #1419
Notifying:
- Username change
- Email change
- Password change
- (Dis)connect github
Move the two-factor authentication notifier in an dedicated class
> Email users on account security changes

- src/Controller/ResetPasswordController.php
Since the form does now the checking we need to remove the check here.
caused by [#56ecc0a42f6d3f08b9a549152e6c0b6d79c8323e](https://github.com/pscheit/packagist-org/commit/56ecc0a42f6d3f08b9a549152e6c0b6d79c8323e)
> Fix that password reset form was invalid all the time

- src/SecurityAdvisory/GitHubSecurityAdvisoriesSource.php
- tests/SecurityAdvisory/GitHubSecurityAdvisoriesSourceTest.php
Noticed for sylius/sylius which has [one](https://github.com/advisories/GHSA-mw82-6m2g-qh6c) and [two](https://github.com/advisories/GHSA-mw82-6m2g-qh6c) advisories for the same CVE
See the [GitHub response](https://github.com/github/advisory-database/issues/3085#issuecomment-1933049782) for reference.
> SecurityAdvisories: skip duplicate GitHub advisories where package name and CVE matches

- src/Entity/SecurityAdvisorySource.php
- tests/SecurityAdvisory/SecurityAdvisoryResolverTest.php
Happened [here](https://github.com/FriendsOfPHP/security-advisories/pull/722) for example. The filename changes but the advisory is still the same and matches.
> SecurityAdvisories: changing the remote ID for the same remote advisory should update the source remote ID

- js/app.js
- src/Controller/ProfileController.php
- templates/user/my_profile.html.twig
- tests/Controller/ProfileControllerTest.php
- translations/messages.en.yml
Resolves https://github.com/composer/packagist/issues/1460 - adds a button for rotating API tokens
If you do not like how this looks, we could potentially hide the button with a query flag like `?show-rotate-api-key=1`. Please let me know what you think!
And upon clicking the button:
> feat: add button for rotating API token

- src/SecurityAdvisory/GitHubSecurityAdvisoriesSource.php
Temporary fix to remove CVEs mentioned in https://phpc.social/@wouterj/113588554019692959
> Symfony: ignore bogus CVEs

- src/SecurityAdvisory/GitHubSecurityAdvisoriesSource.php
GitHub Advisory: https://github.com/advisories/GHSA-2hjh-495w-hmxc
Reason to ignore, see: https://github.com/nca785/CVE-2024-57610
> Sylius: ignore store.sylius.com issue incorrectly filed as general sylius vulnerability

- src/Entity/SecurityAdvisory.php
- tests/Entity/SecurityAdvisoryTest.php
This currently kept calling `$this->updatedAt = $now;` in the big if block because the severity didn't match, but it didn't actually update the severity.
Should resolve https://github.com/composer/packagist/issues/1508
> SecurityAdvisories: GitHub updating the severity of an advisory should store the updated severity

- composer.json
- src/EventListener/OriginListener.php
Just a small change to make local setup work out of the box with the instructions in README, because `symfony serve` runs on port 8000 it won't allow POST requests.
> Local setup: ignore port
